name: mario
channels:
  - pytorch
  - conda-forge
dependencies:
  - matplotlib
  - opencv
  - pip
  - pip:
    - gym-super-mario-bros
  - python=3.8
  - pytorch
  - torchinfo
  - torchvision
  - cudatoolkit=11.3
